# For the Python ecosystem

# Disable annoying attempts to create a keyring for pip
PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

PYENV_ROOT="$HOME/.pyenv"
NLTK_DATA="$HOME/.local/opt/nltk_data"
