# For things are specific to me
PROJECT_HOME="$HOME/work"
COMMONPLACE_ROOT="$HOME/work/commonplace-private"
COMMONPLACE_EDITOR="code --new-window --wait"
AOC_EDITOR="code --new-window"
AOC_ROOT="$HOME/work/advent-of-code"
