
################################################################################
# Variables containing config for common command-line tools
# NB this has to have priority 99 or e.g. EDITOR gets overridden
################################################################################

EDITOR="vim"

LESS="--quit-if-one-screen --ignore-case --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init"

# Coloured gcc warnings and errors
GCC_COLORS="error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01"

# Used for npm -g installs
NPM_CONFIG_PREFIX="$HOME/.local/opt/node"

################################################################################
# For the Python ecosystem
################################################################################

# Disable annoying attempts to create a keyring for pip
PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring

PYENV_ROOT="$HOME/.pyenv"
NLTK_DATA="$HOME/.local/opt/nltk_data"

################################################################################
# Personal tools
################################################################################

PROJECT_HOME="$HOME/work"

# Advent of code
AOC_EDITOR="code --new-window"
AOC_ROOT="$PROJECT_HOME/advent-of-code"

# Commonplace
COMMONPLACE_ROOT="$PROJECT_HOME/commonplace-private"
COMMONPLACE_EDITOR="code --new-window --wait"
